version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
#    image: apikhenko/judo:latest
    build: .
    restart: always
    volumes:
      - static_value:/app/Judo/Judo/static/
      - media_value:/app/Judo/Judo/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/

      # Данные, хранящиеся в томе media_value, будут доступны в контейнере nginx
      # через директорию /var/html/media/
      - media_value:/var/html/media/
#      - ./nginx/certbot/conf:/etc/letsencrypt
#      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      # Контейнер nginx должен быть запущен после контейнера web
      - web

#  certbot:
#    container_name: certbot
#    image: certbot/certbot
#    networks:
#      nginx_net:
#    volumes:
#      - ./nginx/certbot/conf:/etc/letsencrypt
#      - ./nginx/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_value:
  media_value:
